/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author DELL
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
         setResizable(false);
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenidaLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adminBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        logolbl = new javax.swing.JLabel();
        fondolbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenidaLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bienvenidaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidaLbl.setText("BIENVENIDO");
        getContentPane().add(bienvenidaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 360, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SISTEMA DE REGISTRO DE ASISTENCIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 30));

        adminBtn.setBackground(new java.awt.Color(153, 153, 153));
        adminBtn.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        adminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administrador.png"))); // NOI18N
        adminBtn.setText("ADMINISTRADOR");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 180, 50));

        userBtn.setBackground(new java.awt.Color(153, 153, 153));
        userBtn.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        userBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario-de-perfil.png"))); // NOI18N
        userBtn.setText("USUARIO");
        getContentPane().add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 180, 50));

        logolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoUTA.png"))); // NOI18N
        getContentPane().add(logolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        fondolbl.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        fondolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoB.png"))); // NOI18N
        getContentPane().add(fondolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        Login frameCRUD = new Login();
        frameCRUD.setVisible(true);

    // Cerrar o esconder el frame actual si es necesario
        this.dispose();
    }//GEN-LAST:event_adminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JLabel bienvenidaLbl;
    private javax.swing.JLabel fondolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logolbl;
    private javax.swing.JButton userBtn;
    // End of variables declaration//GEN-END:variables
}
